// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
// import Link from "next/link";
// // import Posts from "./productPage/index";
// // import PostDetails from "./products/[id]";
// // import Pokemon from "./pokemon/pokemon";
// // import { Signin } from "./api/auth/signin";
// // import Link from "next/link";
// // import Pokemon from "./pokeomon/pokemon";
// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>My first app</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       {/* <li>
//         <a href="pokemon/pokemon">pokemon</a>
//       </li> */}
//       {/* <Pokemon /> */}
//       <main className={styles.main}>
//         <Link className={styles.link} href="./productPage">
//           Products
//         </Link>
//         {/* <Signin /> */}
//       </main>
//     </>
//   );
// }

// import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import Link from "next/link";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Login from "./login";
import Posts from "./productPage";

const Home = () => {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      {console.log(session?.user)}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {/* create book card */}
          {session && session.user ? (
            <Link className={styles.link} href="./productPage">
              Products
            </Link>
          ) : (
            <Login />
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
